version: "3"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/escoladb\
    restart: always

    environment:
      - POSTGRES_USER=anderson
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=escoladb

    expose:
      - 5432
    networks:
      - backend

  appescola:
    build:
      context: ./
    restart: always

    ports:
      - 5010:5010
    depends_on:
      - postgres
    networks:
      - backend
    expose:
      - 5010
networks:
  backend: {}
